services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    hostname: bazarr
    networks:
      - mediarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /data/stacks/mediarr/configs/mediarr/bazarr:/config
      - jellyfin_media:/mnt/Jellyfin
    ports:
      - 6767:6767
    restart: always
    depends_on:
      - sonarr
      - radarr

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    hostname: jellyseerr
    volumes:
      - /data/stacks/mediarr/configs/mediarr/jellyseerr:/app/config
    networks:
      - mediarr
    ports:
      - 5055:5055
    restart: always
    depends_on:
      - sonarr
      - radarr

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    hostname: prowlarr
    networks:
      - mediarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /data/stacks/mediarr/configs/mediarr/prowlarr:/config
    ports:
      - 9696:9696
    restart: always
    depends_on:
      - flaresolverr

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    hostname: flaresolverr
    ports:
      - 8191:8191
    networks:
      - mediarr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
    restart: always

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    mem_limit: 4G
    hostname: qbittorrent
    networks:
      - mediarr
    environment:
      - WEBUI_PORT=8090
    volumes:
      - /data/stacks/mediarr/configs/mediarr/qbittorrent:/config
      - jellyfin_media:/mnt/Jellyfin
      - jellyfin_downloads:/downloads
    ports:
      - 8090:8090
      - 6881:6881
      - 6881:6881/udp
    restart: always

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr
    networks:
      - mediarr
    environment:
      - PUID=1000
      - PGID=100
    volumes:
      - /data/stacks/mediarr/configs/mediarr/radarr:/config
      - jellyfin_media:/mnt/Jellyfin
      - jellyfin_downloads:/downloads
    ports:
      - 7878:7878
    restart: always
    depends_on:
      - prowlarr
      - qbittorrent

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    hostname: sonarr
    networks:
      - mediarr
    environment:
      - PUID=1000
      - PGID=100
    volumes:
      - /data/stacks/mediarr/configs/mediarr/sonarr:/config
      - jellyfin_media:/mnt/Jellyfin
      - jellyfin_downloads:/downloads
    depends_on:
      - prowlarr
      - qbittorrent
    ports:
      - 8989:8989
    restart: always

volumes:
  jellyfin_media:
    driver: local
    driver_opts:
      type: nfs
      o: addr=NFS-ip,rw
      device: ":/path"
  jellyfin_downloads:
    driver: local
    driver_opts:
      type: nfs
      o: addr=NFS-IP,rw
      device: ":/path/downloads"

networks:
  mediarr:
    driver: bridge
