version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin

    network_mode: 'host'
    group_add:
      - "993"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - /home/docker/jellyfin-server/config:/config
      - /home/docker/jellyfin-server/cache:/cache
      - /mnt/Jellyfin:/media
    restart: unless-stopped
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.kapko.eu
