services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: always
    network_mode: "host"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.xxx.tld

    volumes:
      - jellyfin_media:/media:rw
      - /data/stacks/jellyfin/config:/config:rw
      - /data/stacks/jellyfin/cache:/cache:rw


volumes:
  jellyfin_media:
    driver: local
    driver_opts:
      type: nfs
      o: addr=NFS-IP,rw
      device: ":/path"
